name: volume_vault
version: 0.1.5
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  animations: ^2.0.7
  chips_choice: ^3.0.0
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  eeffects: ^0.0.3
  envied: ^0.3.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3
  firebase_storage: ^11.2.2
  flutter_animate: ^4.0.0
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.0
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  go_router: ^8.0.1
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.2.0
  image_picker: ^0.8.8
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.0
  lottie: ^2.4.0
  lucide_icons: ^0.244.0
  mask_text_input_formatter: ^2.4.0
  mobile_scanner: ^3.2.0
  package_info_plus: ^4.0.2
  palette_generator: ^0.3.3+2
  path: ^1.8.3
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0
  responsive_framework: 0.2.0
  shared_preferences: ^2.0.17
  shimmer: ^3.0.0
  text_scroll: ^0.2.0
  textfield_tags: ^2.0.2
  timelines: ^0.1.0
  url_launcher: ^6.1.9
  webview_flutter: ^4.2.2

  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  pubspec_dependency_sorter: ^1.0.4
  very_good_analysis: ^5.0.0

  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/login_page_image.jpg
    - assets/images/signin_page_image.jpg
    - assets/images/home_page_desktop.jpg
    - assets/images/login_signin_page_divider.jpg
    - assets/animations/no_books.json
    - assets/icon/icon.png
    
  uses-material-design: true
  generate: true
