name: volume_vault
description: A new Flutter project.
publish_to: 'none'

version: 0.1.5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.2.0
  shared_preferences: ^2.0.17
  flutter_secure_storage: ^8.0.0
  responsive_framework: 0.2.0
  google_fonts: ^4.0.3
  palette_generator: ^0.3.3+2
  url_launcher: ^6.1.9
  eeffects: ^0.0.3
  intl: ^0.18.0
  flutter_animate: ^4.0.0
  animations: ^2.0.7
  mask_text_input_formatter: ^2.4.0
  freezed_annotation: ^2.2.0
  dio: ^5.0.1
  envied: ^0.3.0
  infinite_scroll_pagination: ^3.2.0
  flutter_localizations:
    sdk: flutter
  chips_choice: ^3.0.0
  textfield_tags: ^2.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.2
  font_awesome_flutter: ^10.4.0
  go_router: ^8.0.1
  path_provider: ^2.0.15
  path: ^1.8.3
  image_picker: ^0.8.8
  shimmer: ^3.0.0
  lucide_icons: ^0.244.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.2.0
  flutter_slidable: ^3.0.0
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3
  lottie: ^2.4.0
  timelines: ^0.1.0
  text_scroll: ^0.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  envied_generator: ^0.3.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/login_page_image.jpg
    - assets/images/signin_page_image.jpg
    - assets/images/home_page_desktop.jpg
    - assets/images/login_signin_page_divider.jpg
    - assets/animations/no_books.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
