name: volume_vault
description: A new Flutter project.
publish_to: 'none'

version: 0.1.2

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.2.0
  shared_preferences: ^2.0.17
  responsive_framework: ^0.2.0
  google_fonts: ^4.0.3
  palette_generator: ^0.3.3+2
  url_launcher: ^6.1.9
  eeffects: ^0.0.3
  intl: ^0.18.0
  flutter_animate: ^4.0.0
  animations: ^2.0.7
  mask_text_input_formatter: ^2.4.0
  freezed_annotation: ^2.2.0
  dio: ^5.0.1
  envied: ^0.3.0
  realm: ^1.0.2
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  envied_generator: ^0.3.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#3EA6EB"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/login_page_image.jpg
    - assets/images/signin_page_image.jpg
    - assets/images/home_page_desktop.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
