version: '3.9'

networks:
  prom:
  api:

volumes:
  primary-db:
  meili-vol:
  grafana-vol:

services:
  vvinfra-hug:
    container_name: volume_vault_infra_hug
    build:
      context: ./
      dockerfile: Dockerfile.Hug
    environment:
      - ASPNETCORE_ENVIRONMENT
      - API_KEY
      - POSTGRES_CONNECTION_STRING
      - MEILISEARCH_HOST
      - MEILISEARCH_MASTER_KEY
    ports:
      - 5029:80
    networks:
      - api
      - prom
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    networks:
      - api
    volumes:
      - primary-db:/var/lib/postgresql/data
  
  meilisearch:
    container_name: meilisearch
    image:  getmeili/meilisearch
    ports:
      - 7700:7700
    networks:
      - api
    volumes:
      - meili-vol:/meili_data