version: '3.9'

networks:
  prom:
  api:

volumes:
  primary-db:
  meili-vol:
  grafana-vol:

services:
  vvinfra:
    container_name: volume_vault_infra
    build:
      context: ./VolumeVaultInfra/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT
      - JWT_SYMMETRIC_KEY
      - API_KEY
      - VV_POSTGRES_HOST
      - VV_POSTGRES_PORT
      - VV_DEFAULT_POSTGRES_DB_NAME
      - VV_POSTGRES_USER
      - VV_POSTGRES_PASSWORD
      - VV_MONGO_HOST
      - VV_MONGO_PORT
      - VV_MONGO_USER
      - VV_MONGO_PASSWORD
      - VV_MONGO_DB_NAME
      - VV_MEILISEARCH_HOST
      - VV_MEILISEARCH_PORT
      - MEILISEARCH_MASTER_KEY
    ports:
      - 5081:80
    networks:
      - api
      - prom
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    networks:
      - api
    volumes:
      - primary-db:/var/lib/postgresql/data
  
  meilisearch:
    container_name: meilisearch
    image:  getmeili/meilisearch
    ports:
      - 7700:7700
    networks:
      - api
    volumes:
      - meili-vol:/meili_data

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prom
  
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    networks:
      - prom
    volumes:
      - grafana-vol:/var/lib/grafana grafana/grafana-enterprise