version: '3.9'

networks:
  api:
  search:

volumes:
  primary-db:
  meili-vol:
  grafana-vol:

services:
  vvinfra-hug:
    container_name: volume_vault_infra_hug
    build:
      context: ./
      dockerfile: Dockerfile.Hug
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_URLS
      - API_KEY
      - POSTGRES_CONNECTION_STRING
      - MEILISEARCH_HOST
      - MEILISEARCH_MASTER_KEY
      - ASPNETCORE_Kestrel__Certificates__Default__Password
      - ASPNETCORE_Kestrel__Certificates__Default__Path
    ports:
      - 5029:80
      - 5030:443
    networks:
      - api
      - search
    depends_on:
      - postgres
    volumes:
      - ./.aspnet/https:/https:ro
    restart: unless-stopped

  vvinfra-search:
    build:
      context: ./
      dockerfile: Dockerfile.Search
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_URLS
      - SEARCH_API_KEY
      - MEILISEARCH_HOST
      - MEILISEARCH_MASTER_KEY
      - ASPNETCORE_Kestrel__Certificates__Default__Password
      - ASPNETCORE_Kestrel__Certificates__Default__Path
    ports:
      - 7039:80
      - 7040:443
    networks:
      - search
    depends_on:
      - meilisearch
    volumes:
      - ./.aspnet/https:/https:ro
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    networks:
      - api
    volumes:
      - primary-db:/var/lib/postgresql/data
  
  meilisearch:
    container_name: meilisearch
    image:  getmeili/meilisearch
    ports:
      - 7700:7700
    networks:
      - search
    volumes:
      - meili-vol:/meili_data