version: '3.9'

networks:
  prom:
  db:

volumes:
  volumes-db:

services:
  vvinfra:
    container_name: volume_vault_infra
    build:
      context: ./VolumeVaultInfra/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT
      - JWT_SYMMETRIC_KEY
      - POSTGRES_HOST
      - POSTGRES_PORT
      - DEFAULT_POSTGRES_DB_NAME
      - VV_POSTGRES_USER
      - VV_POSTGRES_PASSWORD
    ports:
      - 5081:80
    networks:
      - db
      - prom
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    networks:
      - db
    volumes:
      - volumes-db:/var/lib/postgresql/data

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prom
  
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    networks:
      - prom