name: VolumeVaultInfra CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: restore
      run: dotnet restore VolumeVaultInfra/
    - name: build
      run: dotnet build VolumeVaultInfra/ --no-restore
    - name: Execute unit tests
      run: dotnet test VolumeVaultInfra/ --no-build --no-restore
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3